### ISSUE TITLE
The root of the repo is untidy mess

### ISSUE THREAD

**Issue by KOLANICH** [google/kati#177]
I propose to create some subdirs and move some files to them. At least kati and ckati deserve own dirs.

**Comment by danw** [comment]
I've split kati/ckati out into their own directories in #199

**Comment by KOLANICH** [comment]
Yeah, I saw. Thanks. Unfortunately within ckati dir there are too many files, so usage of GUI tools is a bit hard.

I wonder if the files can be reorganized further into semantically meaningful blocks to make the navigation and viewing the dir easier.
