### ISSUE TITLE
status of recursive make?

### ISSUE THREAD

**Issue by adamfeuer** [google/kati#179]
Hi, I'd like to use kati to build [Nuttx](https://github.com/apache/incubator-nuttx) – ninja would make incremental builds a lot faster. 

However, NuttX's Makefile calls make... I think this is the recursive make case that kati doesn't handle yet. Is that right? 

What's the status on this? Is it planned or in-progress? Is there a branch I could try out...?

**Comment by danw** [comment]
We have no plans to implement recursive make -> ninja, as interesting as that project could be. It's just not necessary for our use cases -- we're working towards removing Make in Android, and that was already a single make instance.

**Comment by adamfeuer** [comment]
@danw Thanks for responding so fast!
