### ISSUE TITLE
Why using c++ instead of go?

### ISSUE THREAD

**Issue by vaneyli** [google/kati#194]
Why now use the c++ instead of go?    Is go slower than c++ in kati?  
thanks :)

**Comment by Colecf** [comment]
Yes, the golang version had performance issues. I don't know the full history of what exactly they were though.

The golang version was just deleted in https://github.com/google/kati/pull/269

**Comment by shinh** [comment]
I believe the main cause was GC. At that time Go did not have a generational GC. Kati allocates a lot of heap which will never freed. I think non-generation GC wastes time to mark-and-sweep regions which will not be freed.
