### ISSUE TITLE
TestKati/stem_middle.mk: Kati generates "a" and "c" directories.

### ISSUE THREAD

**Issue by skymage23** [google/kati#252]
Relevant Makefile:
```
test: a/a.a b.b c/c

a/%.a:
        @echo $*

%.b:
        @echo $*

c/%:
        @echo $*
```

If I go into ${PWD}/out/stem_middle.mk/ckati, I see that two directories, "a" and "b" are created, causing the test to fail.
Make,  however, simply echos the output.   Shouldn't what Make does be the expected behavior of CKati as well?

**Comment by Colecf** [comment]
Fixed in https://github.com/google/kati/pull/255
