### ISSUE TITLE
ifdef is still buggy

### ISSUE THREAD

**Issue by danw** [google/kati#33]
ifdef is still buggy when there is an embedded space in the evaluated variable name. This snippet works in make, but not with kati:

    A := a # comment

    ifdef $(A)
    $(error FAIL)
    else
    $(info PASS)
    endif

    a := b
    ifdef $(A)
    $(info PASS)
    else
    $(error FAIL)
    endif

I don't think we're hitting this anywhere, but I noticed it when looking at the latest change.

**Comment by shinh** [comment]
Good catch! https://github.com/google/kati/commit/d236eb03fbedb65db7b192c5771a6375aeba95ae should have fixed this issue.

I forgot "git add" so I've added testcases in a separate commit: https://github.com/google/kati/commit/760f959ba462687ceaf653d95411bda6e560f281
