### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [google/kati#38]
Hello,
It would be great to have a tagged release so we could include `kati` in the Homebrew core.
Thanks!

**Comment by shinh** [comment]
I'm wondering why homebrew decided to have kati. I think this project is useful only for Android, and Android has this repository in its tree. If there isn't a particular usecase, I'd suggest just removing kati from homebrew.

**Comment by bfontaine** [comment]
We didn’t really *decide* to have it in Homebrew; someone submitted a pull-request to our `HEAD`-only tap (https://github.com/Homebrew/homebrew-head-only/pull/154) and at this time we didn’t thought of a reason not to have it. We have a non-breaking change policy that prevents us from removing a formula so we can’t remove `kati`.

We have a special `HEAD`-only repository for projects without releases which we would like to deprecate. `kati` is there and having a tagged release would allow us to move it in the core. If you don’t tag anything it’s fine; `kati` will stay as is in Homebrew and will continue to work.

**Comment by shinh** [comment]
OK, then let me just close this issue. I cannot imagine the homebrew package will be useful for someone. If I create a tagged release now, I don't think I want to keep updating release tag for the homebrew package no one actually uses. Eventually the tagged version will be just an old version.

If someone find kati useful and want stable releases, I'm happy to start tagging releases, but I doubt it happens.

**Comment by bfontaine** [comment]
Ok, thanks!
