### ISSUE TITLE
Force regen if ninja file is missing

### ISSUE THREAD

**Issue by danw** [google/kati#39]
I told a coworker to force a ninja file regeneration (to test a different bug) by removing the generated ninja file. But kati doesn't realize that it needs to regenerate the ninja file in that case:

```
$ rm out/build-aosp_flounder.ninja
$ m
.....
make: Entering directory `aosp'
Running kati to generate build-aosp_flounder.ninja...
No need to regenerate ninja file
Starting build with ninja
ninja: Entering directory `.'
ninja: error: loading 'out/build-aosp_flounder.ninja': No such file or directory
make: *** [ninja_wrapper] Error 1
make: Leaving directory `aosp'
```

**Comment by shinh** [comment]
Thanks! https://github.com/google/kati/commit/5a5a7f67b1ea6434e5e81cecddba138ff870ff40

**Comment by govindpathak1** [comment]
how to force regen it

**Comment by kirito96** [comment]
@govindpathak1 https://github.com/google/kati/commit/5a5a7f67b1ea6434e5e81cecddba138ff870ff40
