### ISSUE TITLE
Fail early for unsupported automatic variables

### ISSUE THREAD

**Issue by danw** [google/kati#40]
Kati doesn't support all automatic variables -- for the variables it doesn't support, it should error out early instead of acting like they are undefined.

Example: $? -- this should be the prerequisites that are newer than the target. Ninja has no way of supporting this, but it's not often used either.

**Comment by shinh** [comment]
Thanks for the report! https://github.com/google/kati/commit/b552df31a53738f72d273c1e6c43bf2e370c3597
