### ISSUE TITLE
make doesn't work

### ISSUE THREAD

**Issue by mina** [google/kati#44]
almasrymina@almasrymina:~/src/kati$ make
rm -rf out/{src,pkg/*}/github.com/google/kati
mkdir -p out/{src,pkg/*}/github.com/google/kati
cp -a ast.go bootstrap.go buf.go buf_test.go dep.go depgraph.go doc.go evalcmd.go eval.go exec.go expr.go expr_test.go fileutil.go flags.go func.go func_test.go log.go ninja.go ninja_test.go parser.go pathutil.go pathutil_test.go query.go rule_parser.go rule_parser_test.go serialize.go shellutil.go shellutil_test.go stats.go strutil.go strutil_test.go symtab.go var.go version.go worker.go cmd out/src/github.com/google/kati
GOPATH=$(pwd)/out:${GOPATH} go get github.com/google/kati/cmd/kati
import cycle not allowed
package github.com/google/kati/cmd/kati
        imports bytes
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports runtime
make: *** [go_src_stamp] Error 1

**Comment by ukai** [comment]
I believe your go installation is wrong.
It should not compile standard package by running "go get"
