### ISSUE TITLE
[PATCH] Ignore .POSIX:

### ISSUE THREAD

**Issue by stefanb2** [google/kati#48]
GNU make 3.81 silently ignores .POSIX:, so kati should too.

Only effect would be adding "-e" parameter to SHELL command line.

[0001-C-Ignore-.POSIX.txt](https://github.com/google/kati/files/179395/0001-C-Ignore-.POSIX.txt)

**Comment by shinh** [comment]
Thanks for the patch! I think you are not a Google employee. We need ask you to sign "Contributor License Agreements" to accept patches. Could you review and sign it?

https://cla.developers.google.com/clas

Also, your patch doesn't contain your name nor your email address. Could you tell me them so I can set appropriate info (or it's easier for me if you can make PRs)?

**Comment by stefanb2** [comment]
I'm working for a company that is a Google partner. This work has been done on company time and company resources. But this is my private GitHub account, that's why I removed my company email address from the patch. If there is some other channel than GitHub for Google partners to submit fixes/improvements then please point me in the right direction.

If Github is the only channel and forking the project is the preferred method for submitting changes, then I'll have to cherry-pick the changes to the new branch with my private email address.

**Comment by shinh** [comment]
I'm not familiar with our licensing policies around partners. If you want, I can ask the question internally. But yeah, if you can send a PR from your private address and sign the CLA, it's easier for me.

**Comment by stefanb2** [comment]
I'll need to check if I'm allowed to sign the "on behalf of your employer" variant of the CLA. If not then I'll agree with my boss to submit these changes as private contributions.

**Comment by shinh** [comment]
Any update? I chatted with people who are usually working with partner companies. Their answer sounded like asking you or your company to sign the CLA is the only option.

**Comment by stefanb2** [comment]
I've initiated the necessary company internal process to get approval for upstream contributions. Stay tuned....

**Comment by shinh** [comment]
Great, thanks!

**Comment by stefanb2** [comment]
The internal process finally completed and I pushed my changes to my fork. Please have a look at the cumulative PR #58.
