### ISSUE TITLE
support for `else conditional-directive`

### ISSUE THREAD

**Issue by DanAlbert** [google/kati#52]
https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html

```make
conditional-directive-one
text-if-one-is-true
else conditional-directive-two
text-if-two-is-true
else
text-if-one-and-two-are-false
endif
```

But if I use that syntax with kati:

```
build/core/target_test_internal.mk:12: warning for parse error in an unevaluated line: *** invalid syntax in conditional.                                                                                 [62/9586]
build/core/target_test_internal.mk:14: warning for parse error in an unevaluated line: *** only one `else' per conditional.
build/core/target_test_internal.mk:16: warning for parse error in an unevaluated line: *** only one `else' per conditional.
```

**Comment by danw** [comment]
We use this syntax in quite a few places, so I'd be surprised if this is a kati problem. I'm assuming this is related to this change https://android-review.googlesource.com/#/c/209781/1/core/target_test_internal.mk

    else ifneq ($(filter stlport_,$(LOCAL_NDK_STL_VARIANT)))

it looks like that is an invalid syntax, you're missing the second argument to ifneq:

    else ifneq ($(filter stlport_,$(LOCAL_NDK_STL_VARIANT)),)

**Comment by DanAlbert** [comment]
Oops. That's correct. The error message is rather misleading though.
