### ISSUE TITLE
Missing endif silently ignored

### ISSUE THREAD

**Issue by danw** [google/kati#55]
When a line continuation would eat the endif of a conditional:

```
main:
        echo "FAIL"

ifeq (0,1)
A := 1 \
endif

$(error $(A))
```

Make returns an error about a missing endif:

```
Makefile:9: *** missing `endif'.  Stop.
```

But kati just silently ignores the rest of the file:

```
echo "FAIL"
FAIL
```

**Comment by colincross** [comment]
kati fails for this too:
```main:
	echo "FAIL"

ifeq (0,1)```

```make -f foo.mk
foo.mk:5: *** missing `endif'.  Stop.
```

```ckati -f foo.mk
echo "FAIL"
FAIL
```

kati is not checking for missing endif at all

**Comment by colincross** [comment]
And fails for missing endef too.
