### ISSUE TITLE
multi_implicit_output_patterns test fails for GNU make 4.0

### ISSUE THREAD

**Issue by stefanb2** [google/kati#67]
When executed with GNU make 4.0 it prints "FAIL" in the expected output which causes runtest.rb to abort the whole test suite.

I'm not sure what the correct approach is to fix version dependencies in tests. It seems that GNU make 4.0 always executes the recipe for the dependency of b.c.z.

**Comment by shinh** [comment]
Suppressed the check for GNU make 4. I'm mainly using 3.81 on Linux for development and sometimes try fixing test failures with GNU make 4. It' my bad there's no policy for this kind of cases where two GNU make versions disagree. I think for most cases kati is trying to be similar to 3.81 but sometimes it follows the behavior of 4.

Feel free to suppress test cases like my change when it's impossible to make kati agree with both GNU make versions. Or, you could ignore failures which were failing even without your change, as long as the failure doesn't terminate runtest.rb like this issue.

**Comment by stefanb2** [comment]
fixed by https://github.com/google/kati/commit/855fea499f0527bf2bff59962dbecb27bb590ffa
