### ISSUE TITLE
Allow to echo @commands

### ISSUE THREAD

**Issue by luca020400** [google/kati#70]
I was wondering why @echo isn't treated like normal echo
With this small [patch](http://ix.io/AFo) I was able to get it working properly
Are there any downsides allowing @echo ?
Thanks

**Comment by shinh** [comment]
Sorry, but I don't understand your problem. Everything are working as expected:

> $ cat <<EOF > tmp.mk
> all:
> 	@echo foo
> EOF
> $ ./ckati -f tmp.mk
> foo
> $ ./ckati --ninja -f tmp.mk && ninja
> [1/1] build all
> foo
> $ ./ckati --ninja --detect_android_echo -f tmp.mk && ninja
> [1/1] foo

Perhaps you are using kati with Android tree and don't like --detect_android_echo?

**Comment by luca020400** [comment]
Apperently ckati generates the build.ninja properly, m2n doesn't
ninja doesn't decode ascii colors in the description field and m2n set the text after @echo as description ( ckati doesn't )

`cat Makefile        
all:
	@echo -e "\033[0;31mTest\033[0m"

m2n && ninja
[1/1] -e \033[0;31mTest\033[0m
ckati --ninja && ninja
[1/1] build all
Test
`

**Comment by shinh** [comment]
m2n is for Android so it specifies --detect_android_echo. Please just stop using m2n.
