### ISSUE TITLE
How to call a shell command and use its return value in Makefile when using Kati?

### ISSUE THREAD

**Issue by guwangfeng** [google/kati#71]
I have a Makefile in which some statements relies on the $(shell ...) function. For example:

$(eval SYSTEM_FS_SIZE := $(shell du -sm $(TARGET_OUT)))

But the "commit 28da2379c3b819088f0a503fcd0bfdd27ab40879" (description: [C++] Explicitly disallow $(shell) in other make constructs ) explicitly disallows such usage. And the following error occurs:

kati doesn't support passing results of $(shell) to other make constructs: du -sm out/target/product/aa997/system, Expr(du -sm , SymRef(TARGET_OUT))
 build/core/ninja.mk:159: recipe for target 'out/build-aa997_native.ninja' failed

So my question is: How to call a shell command and use its return value in Makefile when using Kati?

**Comment by shinh** [comment]
I think you can replace it by a shell-script. For example, if you have

> test:
> 	$(eval size:=$(shell du -hs /tmp))
> 	@echo $(size)

you can rewrite it as

> test:
> 	@size=$$(du -hs /tmp); \
> 	echo $${size}

**Comment by guwangfeng** [comment]
Thanks! I'll have a try.
