### ISSUE TITLE
Anyway to completely rebuild a new system image?

### ISSUE THREAD

**Issue by guwangfeng** [google/kati#78]
Hi,

I ecountered an issue when I want to rebuild a system image:

I built a system.img use command:
  make -j4

then there has system.img in out/target/product/....
I found if I deleted the system.img then used:
   make systemimage 
It only copy a system.img from:
    target/product/obj/PACKAGING/systemimage_intermediates/
Once I deleted the target/product/obj/PACKAGING/systemimage_intermediates/system.img
then run 
    make systemimage, 
a error occurred:
 cannot find target/product/obj/PACKAGING/systemimage_intermediates/system.img
make failed

The question is, it can't find the system.img, why the Android can't rebuilt a new one? the system.img is come from the system dictionary.

Even I have modify the Makefile in buile/core, it also don't rebuilt ,just copy

**Comment by shinh** [comment]
> I deleted the target/product/obj/PACKAGING/systemimage_intermediates/system.img

I think this is the right way if you meant $OUT/obj/PACKAGING/systemimage_intermediates/system.img ($OUT is out/target/product/generic if you are using aosp_arm-eng for example). I'm not sure why the subsequent make failed for you. Anyway this sounds like an Android/GNU make question rather than a bug of kati.

**Comment by guwangfeng** [comment]
But in Android5.1, I do the same thing: rm system.img from  $OUT/obj/PACKAGING/systemimage_intermediates/system.img 
it will rebuild.
Would you tell me that,  how can I trigger a re-built system.img? make clean & make systemimage will cost longer time .

**Comment by danw** [comment]
This really isn't a kati question, but an android question, so the android-building mailing list may be a better place for these questions.

Removing $OUT/obj/PACKAGING/systemimage_intermediates/system.img from an AOSP master build triggers a rebuild for me. Are you using the master branch, or something else?

"m snod" (Systemimage NO Dependencies) should also force a rebuild of the system image. "m installclean" is also a cheaper option to use than "m clean".

One thing that's gotten a lot better with kati is that we shouldn't be rebuilding anything unless necessary (and at the same time, we've gotten better at actually rebuilding when necessary). That being said, we don't have great dependencies for what should be installed into the system image, mainly in cases where the user has asked to install something that's not normally installed.

**Comment by shinh** [comment]
If needed, please continue the discussion in https://groups.google.com/forum/#!forum/android-building
