### ISSUE TITLE
Doesn't seem to be working for me. But I don't totally know what I'm doing...

### ISSUE THREAD

**Issue by codeseven58** [google/kati#80]
I followed the instructions by copying and pasting. I think I got the $PATH correct too.

> if [ -d "$HOME/src/kati" ] ; then
    PATH="$HOME/src/kati:$PATH"
fi

When I run the script ./ninja.sh I get 
./ninja.sh: 5: exec: ninja: not found

Can you tell me what I did wrong?

**Comment by shinh** [comment]
Please install ninja (https://github.com/ninja-build/ninja). Anyway, if you didn't know ninja, I guess you don't need kati..
