### ISSUE TITLE
Bad error message for something that's questionably valid

### ISSUE THREAD

**Issue by danw** [google/kati#83]
This isn't what people want to do anyway, but the error message looks like a kati problem, when it's really a Makefile problem (and maybe a kati problem if what is breaking is technically valid):

Makefile:
```
define var
VAR:=1
endef

$(call var)

$(info SUCCESS)
```

make output:
```
SUCCESS
make: *** No rule to make target `=1', needed by `VAR'.  Stop.
```

ckati output:
```
parser.cc:584: sep != 0
```

**Comment by shinh** [comment]
Here's another testcase for the record:

> test: =foo
